### PR TITLE
Added new commands

### PR DESCRIPTION
**Pull request by dliocode**
New commands
* HKEYS
* HVALS
* HEXISTS
* HLEN
* HINCRBY
* HINCBRYFLOAT

### CODE REVIEW

**Comment by dliocode** [comment]
Hello, can you generate a Release of the new features?

My team uses a dependency tool based on Releases..

If you are interested, you can see it here: [boss](https://github.com/HashLoad/boss).

**Comment by danieleteti** [comment]
Thank you. I'll build new release ASAP.

**Comment by dliocode** [comment]
If you need any help, I would like to collaborate more!

**Comment by danieleteti** [comment]
v2.1 is here. Check on your side please (https://github.com/danieleteti/delphiredisclient/releases/tag/v2.1)

**Comment by dliocode** [comment]
Thank you

Em Ter, 5 de jan de 2021 11:30, Daniele Teti <notifications@github.com>
escreveu:

**Pull request merged**
